spring:
  application:
    name: todolist
  datasource:
    url: jdbc:postgresql://localhost:5432/todolistdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# JavaMelody configuration
javamelody:
  management-endpoint-monitoring-enabled: true
  # Enable JavaMelody auto-configuration (optional, default: true)
  # enabled: true
  # Data source names to exclude from monitoring (optional, comma-separated)
  # excluded-datasources: secretSource,topSecretSource
  # Enable monitoring of Spring services and controllers (optional, default: true)
  # spring-monitoring-enabled: true
  # Initialization parameters for JavaMelody (optional)
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # log http requests:
    log: true

    # to exclude images, css, fonts and js urls from the monitoring:
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)

    # to aggregate digits in http requests:
    #http-transform-pattern: \d+

    # to add basic auth:
    #authorized-users: admin:adminpwd

    # to change the default storage directory:
    #storage-directory: /tmp/javamelody

    # to change the default "/monitoring" path:
    #monitoring-path: /admin/performance

# Spring Boot Actuator configuration
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - monitoring
