### Update a task
PUT http://localhost:8080/tasks/3
Content-Type: application/json

{
  "title": "Buy milk",
  "description": "Need to buy milk from the store"
}

### Update another task
PUT http://localhost:8080/tasks/4
Content-Type: application/json

{
  "title": "Buy eggs",
  "description": "Need to buy eggs from the store as soon as possible"
}
