### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy milk",
  "description": "Need to buy milk from the store"
}

### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy eggs",
  "description": "Need to buy eggs from the store"
}

### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy bread",
  "description": "Need to buy bread from the store"
}

### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy butter",
  "description": "Need to buy butter from the store"
}

### Create a new task
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy cheese",
  "description": "Need to buy cheese from the store"
}

### Create a new task with invalid data
POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Buy milk"
}

### Get all tasks
GET http://localhost:8080/tasks

### Get a task
GET http://localhost:8080/tasks/67051426266dae2cf3f70dd6

### Update a task
PUT http://localhost:8080/tasks/6705fbd5e873282694357f88
Content-Type: application/json

{
  "title": "Buy milk",
  "description": "Need to buy milk from the store"
}

### Update another task
PUT http://localhost:8080/tasks/6705fbcfe873282694357f85
Content-Type: application/json

{
  "title": "Buy eggs",
  "description": "Need to buy eggs from the store as soon as possible"
}

### Delete a task
DELETE http://localhost:8080/tasks/6705fbcfe873282694357f85

### Complete a valid task
PATCH http://localhost:8080/tasks/6705fbcbe873282694357f84/complete

### Complete an invalid task
PATCH http://localhost:8080/tasks/6705fbcbe873282694357f84/complete

### Reopen a valid task
PATCH http://localhost:8080/tasks/6705fbcbe873282694357f84/reopen

### Reopen an invalid task
PATCH http://localhost:8080/tasks/6705fbcbe873282694357f84/reopen
